sudo: required

language: c

services:
- docker

# Don't download the compiler and Verilator (which aren't built here and
# are large)
git:
  submodules: false

# Dockerfile is here: https://github.com/jbush001/NyuziBuildContainer
before_install:
- docker pull jeffbush001/nyuzi-build	

script:
- docker run -v $TRAVIS_BUILD_DIR:/root/NyuziProcessor -w /root/NyuziProcessor jeffbush001/nyuzi-build /bin/bash -c build/run_ci_tests.sh

