sudo: required

language: c

services:
- docker

# Don't pull the compiler and Verilator sources (which aren't built here and
# are large)
git:
  submodules: false

# Pull a container from DockerHub that has Verilator and the Nyuzi toolchain.
# It is created using build/Dockerfile and build/build-container.sh.
# The variable $DOCKER_REPO is set in the Travis CI configuration settings
# for this project.
before_install:
- docker pull $DOCKER_REPO

# Mount the source directory in the container and set that to be the working
# directory. Then launch the script build/run_ci_tests.sh from this repository,
# which will do the rest.
script:
- docker run -v $TRAVIS_BUILD_DIR:/root/NyuziProcessor -w /root/NyuziProcessor $DOCKER_REPO /bin/bash -c build/run_ci_tests.sh

